version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: delman

  app:
    image: flask_app
    depends_on:
      - db
    ports:
    - 5000:5000
    environment:
      BOILERPLATE_ENV: prod