"""empty message

Revision ID: 59d54b8a7a71
Revises: 8a0398a6449d
Create Date: 2022-05-22 06:41:08.707093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59d54b8a7a71'
down_revision = '8a0398a6449d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('bod', sa.Date(), nullable=True),
    sa.Column('no_ktp', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('vaccine_type', sa.String(length=255), nullable=True),
    sa.Column('vaccine_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no_ktp')
    )
    op.drop_constraint('employee_full_name_key', 'employee', type_='unique')
    op.drop_constraint('user_full_name_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_full_name_key', 'user', ['full_name'])
    op.create_unique_constraint('employee_full_name_key', 'employee', ['full_name'])
    op.drop_table('patient')
    # ### end Alembic commands ###
